### ISSUE TITLE
how to use in laravel

### ISSUE THREAD

**Issue by Xanyone** [mix-php/mix-auth#3]
hello,i want to use in laravel,I checked the source code ，Need to rely on bean to achieve injection，Do you need to modify anything if you use it in laravel

**Comment by onanying** [comment]
@Tylorwill If you mind the dependency of the bean, in fact, you can directly use firebase/php-jwt, which is better

**Comment by Xanyone** [comment]
> If you mind the dependency of the bean, in fact, you can directly use firebase/php-jwt, which is better

ok。thank you
